import {Inter} from 'next/font/google'
import './globals.css'
import Header from "@/components/headers/Header";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ['latin'], weight:["400", "500", "600", "700", "800"]})

export const metadata = {
    title: 'Kids&apos; Coding Adventure',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" className={"scroll-smooth md:scroll-pt-[2.5rem]"}>
        <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
